apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx-test
  annotations:
    external-dns.alpha.kubernetes.io/hostname: nginx.stilo.ca
spec:
  selector:
    app.kubernetes.io/name: nginx
  ports:
  - name: http
    targetPort: 80
    port: 80

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  namespace: nginx-test
  labels:
    app.kubernetes.io/name: nginx
spec:
  replicas: 3
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx
  namespace: nginx-test
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`www.nginx.stilo.ca`)
      kind: Rule
      services:
        - name: nginx
          port: 80
    - match: Host(`nginx.stilo.ca`)
      kind: Rule
      services:
        - name: nginx
          port: 80
      middlewares:
        - name: default-headers
  tls: {}
