---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-test
spec: {}

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-internal
  namespace: nginx-test
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-internal
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-internal
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 80
            name: http

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-internal
  namespace: nginx-test
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nginx
  ports:
  - name: http
    targetPort: 80
    port: 80

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-internal
  namespace: nginx-test
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - https-internal
  routes:
    - match: Host(`nginx-internal.stilo.ca`)  
      kind: Rule
      services:
        - name: nginx-internal
          port: 80
      middlewares:
        - name: default-headers
  tls: {}


