#1
apiVersion: v1
kind: Secret
metadata:
  name: dashboard-basic-auth-creds
  namespace: traefik
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: admin

---

#2
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: dashboard-basic-auth
  namespace: traefik
spec:
  basicAuth:
    secret: dashboard-basic-auth-creds

---

#3
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
  namespace: traefik
spec:
  entryPoints:
    - traefik
  routes:
    - kind: Rule
      match: Host(`traefik.stilo.ca`) #4
      middlewares:
        - name: dashboard-basic-auth
          namespace: traefik
      services:
        - kind: TraefikService
          name: api@internal